### ESERCIZIO 3 DI PAGINA 107 DEL LIBRO
#### simulare diecimila partite ciascuna composta da 1000 lanci di una moneta.In quante partite si riscontra almeno il 55% di croci sui 1000 lanci?

In [483]:
import numpy as np

In [484]:
numero_partite = 10000
numero_partite

10000

In [485]:
numero_lanci = 1000
numero_lanci

1000

In [486]:
lanci = np.random.randint(0,2,(numero_partite,numero_lanci))
lanci

array([[1, 1, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 0, 0, 0]])

In [487]:
croci_trovate = np.sum(lanci, axis = 1)
croci_trovate

array([496, 493, 495, ..., 495, 518, 518])

In [488]:
percentuale_croci = 0.55 * numero_lanci
partite_croci = np.sum(croci_trovate >= percentuale_croci)
partite_croci

15

## ESERCIZIO 5 PAGINA 1077
#### Considera un array monodimensionale di numeri e trova la posizione di tutti i massimi locali. Per esempio, dato l’array a = [0, 2, 1, 1, 3, 2], 2 e 3 sono massimi locali rispettivamente nelle posizioni 1 e 4. 

In [489]:
array = np.array([0,2,1,1,3,2])
array

array([0, 2, 1, 1, 3, 2])

In [490]:
posizioni_massimi = []

In [491]:
array_dx = np.roll(array, +1)
array_dx

array([2, 0, 2, 1, 1, 3])

In [492]:
array_sx = np.roll(array, -1)
array_sx

array([2, 1, 1, 3, 2, 0])

In [493]:
for i in range(1, len(array)-1):
    if[(array[i] > array_sx) & array[i] > array_dx]:
        posizioni_massimi.append(i) 


posizioni_massimi

[1, 2, 3, 4]

## ESERCIZIO 6 PAGINA 107
#### Considera un array monodimensionale di numeri inte- ri compresi tra 0 e 9, generato casualmente, e trova le posizioni dell’array in cui compare la sequenza di nu- meri [1, 2, 3].

In [494]:
array = np.random.randint(1,4, size= 10)
array

array([2, 1, 2, 3, 1, 3, 3, 2, 1, 2])

In [495]:
sequenza = np.array([1,2,3])
sequenza

array([1, 2, 3])

In [496]:
posizioni = []

In [497]:
for i in range (0,len(array)- 2):
    if(array[i] == sequenza[0]):
        if(array[i+1] == sequenza[1]):
            if ((array[i+2] == sequenza[2]) ):
                posizioni.append(i)
                posizioni.append(i+1)
                posizioni.append(i+2)


posizioni




[1, 2, 3]

## ESERCIZIO 9 PAGINA 107
#### Due giocatori si affrontano in una partita a dadi: ogni volta che un giocatore ottiene un numero maggiore del suo rivale guadagna un punto, mentre se entrambi i giocatori ottengono lo stesso numero guadagnano mezzo punto ciascuno. i Simula una partita di 1000 lanci e registra i risultati di 10 partite. i Se un giocatore utilizzasse un dado truccato in cui il 5 e il 6 avessero una probabilità doppia di uscire rispetto agli altri numeri, potremmo riuscire a ca- pirlo?

In [498]:
risultati_normali = []

In [499]:
for _ in range(10):
    dado_standard = np.random.randint(1, 7, size=10)
    print(dado_standard)
    dado_standard2 = np.random.randint(1, 7, size=10)
    print(dado_standard2)
    punteggio_giocatore_1 = np.sum(dado_standard > dado_standard2)
    punteggio_giocatore_2 = np.sum(dado_standard < dado_standard2)
    punteggio_giocatore_1 += 0.5 * np.sum(dado_standard == dado_standard2)
    punteggio_giocatore_2 += 0.5 * np.sum(dado_standard == dado_standard2)
    
    risultati_normali.append((punteggio_giocatore_1, punteggio_giocatore_2))

[6 3 6 1 1 6 5 2 6 1]
[2 4 3 3 1 2 6 2 2 5]
[3 4 4 1 2 3 2 4 6 5]
[4 2 5 1 1 1 1 1 3 3]
[4 4 2 4 4 1 2 2 5 2]
[4 6 1 2 6 1 1 5 4 5]
[1 6 4 5 3 1 3 3 6 2]
[6 3 3 4 3 6 2 3 4 5]
[1 6 1 4 2 2 4 4 6 5]
[3 3 6 5 5 6 1 6 1 2]
[4 3 5 5 5 5 1 3 4 2]
[2 6 3 5 2 4 4 2 4 5]
[2 1 5 6 1 1 1 1 2 1]
[2 5 2 4 2 3 6 5 5 3]
[5 5 2 5 3 3 2 3 1 3]
[2 1 3 3 5 6 3 6 3 6]
[3 5 5 4 3 1 4 5 6 5]
[6 6 2 2 6 6 6 2 5 5]
[2 3 6 1 2 2 2 5 3 6]
[3 3 5 3 3 1 1 6 1 2]


In [500]:
print(risultati_normali)

[(5.0, 5.0), (7.5, 2.5), (5.0, 5.0), (6.0, 4.0), (4.0, 6.0), (6.0, 4.0), (2.5, 7.5), (3.0, 7.0), (4.5, 5.5), (5.5, 4.5)]


## ESERCIZIO 10 PAGINA 107
##### Nel parco vicino alla scuola è installata una centrali- na per la misurazione del livello di polveri sottili PM10 nell’aria. Talvolta la centralina va in uno stato di errore per cui la misurazione delle PM10 fallisce e il dato cor- rispondente riporta il valore 9999,9 all’interno dell’ar- ray delle misurazioni dati. Crea un array di 1000 campioni che generino dei valori secondo una distribuzione normale con valore medio 19 e varianza 5 e supponi che la centralina sia andata in errore 20 volte. Con l’array così creato: i individua se ci sono due dati errati in finestre di al massimo 5 misurazioni consecutive e segnala che la centralina deve essere riparata; i ripulisci i dati dai valori errati e calcola media, mas- simo e minimo

In [501]:
campioni = np.random.normal(19, np.sqrt(5), 1000)
campioni

array([16.56384569, 19.84319618, 14.38774141, 19.19783124, 18.21981122,
       18.07084551, 21.43424295, 20.08767861, 22.84109612, 20.95250259,
       13.75741078, 17.34330521, 17.78609991, 19.16581967, 18.10869612,
       19.78923731, 18.8260885 , 15.88482033, 24.97077349, 20.17127297,
       24.2696785 , 23.12921421, 19.8704258 , 19.98916515, 18.46227548,
       17.13229952, 19.5154312 , 15.83952698, 19.607152  , 20.86740298,
       17.45397109, 19.40462334, 15.19448806, 21.08260339, 19.18522251,
       21.48945623, 19.13640152, 15.33985071, 19.94414277, 18.08997774,
       18.17464107, 18.81130868, 20.44536792, 17.98226359, 20.82669295,
       19.3937495 , 19.64270403, 20.87152854, 16.06116412, 15.58013198,
       17.38274731, 16.51462469, 19.82145589, 17.41886496, 21.69154248,
       18.56341563, 23.94396005, 20.02662694, 21.53812674, 20.29205152,
       21.29881711, 19.75716615, 19.05665194, 17.51224776, 15.60166625,
       22.63680387, 17.00286273, 13.866689  , 19.09758661, 19.54

In [502]:
errori = np.random.choice(1000,20, replace = False)
errori

array([129, 200, 133, 820, 120, 912, 695, 401, 545, 853, 842,  90, 855,
       309, 729, 320, 918, 245, 643, 206])

In [503]:
campioni[errori] = 9999.9
campioni

array([  16.56384569,   19.84319618,   14.38774141,   19.19783124,
         18.21981122,   18.07084551,   21.43424295,   20.08767861,
         22.84109612,   20.95250259,   13.75741078,   17.34330521,
         17.78609991,   19.16581967,   18.10869612,   19.78923731,
         18.8260885 ,   15.88482033,   24.97077349,   20.17127297,
         24.2696785 ,   23.12921421,   19.8704258 ,   19.98916515,
         18.46227548,   17.13229952,   19.5154312 ,   15.83952698,
         19.607152  ,   20.86740298,   17.45397109,   19.40462334,
         15.19448806,   21.08260339,   19.18522251,   21.48945623,
         19.13640152,   15.33985071,   19.94414277,   18.08997774,
         18.17464107,   18.81130868,   20.44536792,   17.98226359,
         20.82669295,   19.3937495 ,   19.64270403,   20.87152854,
         16.06116412,   15.58013198,   17.38274731,   16.51462469,
         19.82145589,   17.41886496,   21.69154248,   18.56341563,
         23.94396005,   20.02662694,   21.53812674,   20.29205

In [504]:
finestra_errori_consecutivi = 5
k = 0
for i in campioni:
    if i == 9999.9:
        k +=1
        if k >= finestra_errori_consecutivi:
            print("La centralina deve essere aggiustata")
            break
        else:
            k = 0

In [505]:
campioni_puliti = campioni[campioni != 9999.9]
campioni_puliti

array([16.56384569, 19.84319618, 14.38774141, 19.19783124, 18.21981122,
       18.07084551, 21.43424295, 20.08767861, 22.84109612, 20.95250259,
       13.75741078, 17.34330521, 17.78609991, 19.16581967, 18.10869612,
       19.78923731, 18.8260885 , 15.88482033, 24.97077349, 20.17127297,
       24.2696785 , 23.12921421, 19.8704258 , 19.98916515, 18.46227548,
       17.13229952, 19.5154312 , 15.83952698, 19.607152  , 20.86740298,
       17.45397109, 19.40462334, 15.19448806, 21.08260339, 19.18522251,
       21.48945623, 19.13640152, 15.33985071, 19.94414277, 18.08997774,
       18.17464107, 18.81130868, 20.44536792, 17.98226359, 20.82669295,
       19.3937495 , 19.64270403, 20.87152854, 16.06116412, 15.58013198,
       17.38274731, 16.51462469, 19.82145589, 17.41886496, 21.69154248,
       18.56341563, 23.94396005, 20.02662694, 21.53812674, 20.29205152,
       21.29881711, 19.75716615, 19.05665194, 17.51224776, 15.60166625,
       22.63680387, 17.00286273, 13.866689  , 19.09758661, 19.54

In [506]:
max = np.max(campioni_puliti)
min = np.min(campioni_puliti)

In [507]:
print("massimo:", max)
print("minimo:", min)

massimo: 26.252423428421874
minimo: 11.676151800355743


## ESERCIZIO 4 PAGINA 107
#### testo qui


In [508]:
classi = 1000
alunni = 25

In [509]:
compleanni = np.random.randint(1, 366, size=(classi, alunni))
compleanni

array([[306, 230, 216, ..., 294,  44, 101],
       [164, 137,   6, ...,  92, 208,  71],
       [ 25, 105, 207, ..., 277, 129,  90],
       ...,
       [307, 251, 304, ..., 353,  71, 213],
       [350, 272, 284, ...,  85, 205, 251],
       [210, 121, 252, ...,  88, 235, 149]])

In [510]:
duplicati_per_classe = np.array([np.size(np.unique(classe)) < alunni for classe in compleanni])
duplicati_per_classe


array([ True,  True, False, False,  True, False, False, False,  True,
       False,  True,  True, False, False,  True,  True, False, False,
        True,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True, False, False, False, False,  True,  True, False, False,
       False,  True, False,  True, False,  True,  True,  True, False,
        True, False,  True,  True, False,  True, False,  True,  True,
       False,  True, False,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True, False,
       False, False,  True, False,  True,  True, False,  True, False,
        True,  True, False, False, False, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True, False, False,  True, False,
        True, False,

In [511]:
classi_con_duplicati = np.sum(duplicati_per_classe)
print(classi_con_duplicati)

586
